name: Deploy

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Install dependencies
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          npm install -g mermaid.cli

      - name: Install ImageMagick
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick

      - name: Set deploy options
        id: setup
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          if [[ "${GITHUB_REF}" == refs/pull/*/merge ]]; then
            echo "SRC_BRANCH=${GITHUB_HEAD_REF}" >> "$GITHUB_OUTPUT"
            echo "NO_PUSH=--no-push" >> "$GITHUB_OUTPUT"
          elif [[ "${GITHUB_REF}" == refs/heads/* ]]; then
            echo "SRC_BRANCH=${GITHUB_REF#refs/heads/}" >> "$GITHUB_OUTPUT"
          fi

          echo "DEPLOY_BRANCH=gh-pages" >> "$GITHUB_OUTPUT"

      - name: Deploy website
        run: |
          echo "y" | bash bin/deploy --verbose \
            ${{ steps.setup.outputs.NO_PUSH }} \
            --src ${{ steps.setup.outputs.SRC_BRANCH }} \
            --deploy ${{ steps.setup.outputs.DEPLOY_BRANCH }}
